export type NewsCategory = 'プレスリリース' | 'サービス' | 'お知らせ'

export type NewsItem = {
  slug: string
  date: string
  category: NewsCategory
  title: string
  description: string
  body: string[]
}

export const newsCategories = ['すべて', 'プレスリリース', 'サービス', 'お知らせ'] as const

export const newsItems: NewsItem[] = [
  {
    slug: 'selmo-service-page-2026-06-20',
    date: '2026.06.20',
    category: 'サービス',
    title: 'selmo. サービス紹介ページを公開しました',
    description: 'サービス概要や特徴をご確認いただけるページを公開しました。',
    body: ['サービス概要や特徴をご確認いただけるページを公開しました。'],
  },
  {
    slug: 'selmo-ai-roleplay-2026-06-12',
    date: '2026.06.12',
    category: 'サービス',
    title: 'selmo. AIロープレ機能を公開しました',
    description: '営業練習を支援するAIロールプレイ機能を公開しました。',
    body: ['営業練習を支援するAIロールプレイ機能を公開しました。'],
  },
  {
    slug: 'selmo-call-analysis-2026-06-05',
    date: '2026.06.05',
    category: 'サービス',
    title: 'selmo. テレアポ分析機能を追加しました',
    description: '架電内容を分析できる機能を追加しました。',
    body: ['架電内容を分析できる機能を追加しました。'],
  },
  {
    slug: 'selmo-logo-2026-06-01',
    date: '2026.06.01',
    category: 'お知らせ',
    title: 'selmo. ブランドロゴを公開しました',
    description: 'selmo.のサービスロゴを公開しました。',
    body: ['selmo.のサービスロゴを公開しました。'],
  },
  {
    slug: 'selmo-development-start-2026-05-25',
    date: '2026.05.25',
    category: 'サービス',
    title: '営業AI「selmo.」の開発を開始しました',
    description: '営業活動の可視化と教育支援を目的とした開発を開始しました。',
    body: ['営業活動の可視化と教育支援を目的とした開発を開始しました。'],
  },
  {
    slug: 'commo-beauty-salon-2026-05-20',
    date: '2026.05.20',
    category: 'サービス',
    title: 'commo. 美容室向け提供を開始しました',
    description: '美容室向け予約導線サービスとして提供を開始しました。',
    body: ['美容室向け予約導線サービスとして提供を開始しました。'],
  },
  {
    slug: 'commo-hotel-2026-05-15',
    date: '2026.05.15',
    category: 'サービス',
    title: 'commo. ホテル向け提供を開始しました',
    description: '宿泊施設向けの導入提供を開始しました。',
    body: ['宿泊施設向けの導入提供を開始しました。'],
  },
  {
    slug: 'commo-site-2026-05-05',
    date: '2026.05.05',
    category: 'プレスリリース',
    title: 'commo. サービスサイトを公開しました',
    description: 'commo.の公式サービスサイトを公開しました。',
    body: ['commo.の公式サービスサイトを公開しました。'],
  },
  {
    slug: 'commo-liff-2026-04-25',
    date: '2026.04.25',
    category: 'サービス',
    title: 'commo. LIFF連携機能を実装しました',
    description: 'LINEアカウントとの連携機能を実装しました。',
    body: ['LINEアカウントとの連携機能を実装しました。'],
  },
  {
    slug: 'commo-service-page-2026-04-20',
    date: '2026.04.20',
    category: 'サービス',
    title: 'commo. サービス紹介ページを公開しました',
    description: 'サービス概要ページを公開しました。',
    body: ['サービス概要ページを公開しました。'],
  },
  {
    slug: 'commo-reservation-admin-2026-04-15',
    date: '2026.04.15',
    category: 'サービス',
    title: 'commo. 予約管理画面の開発を開始しました',
    description: '管理者向け予約管理機能の開発を開始しました。',
    body: ['管理者向け予約管理機能の開発を開始しました。'],
  },
  {
    slug: 'commo-logo-2026-04-10',
    date: '2026.04.10',
    category: 'お知らせ',
    title: 'commo. ブランドロゴを公開しました',
    description: 'commo.のブランドロゴを公開しました。',
    body: ['commo.のブランドロゴを公開しました。'],
  },
  {
    slug: 'commo-development-start-2026-04-05',
    date: '2026.04.05',
    category: 'サービス',
    title: 'LINE予約サービス「commo.」の開発を開始しました',
    description: 'LINEを活用した予約導線構築サービスの開発を開始しました。',
    body: ['LINEを活用した予約導線構築サービスの開発を開始しました。'],
  },
  {
    slug: 'roomly-site-2026-04-01',
    date: '2026.04.01',
    category: 'プレスリリース',
    title: 'Roomly. サービスサイトを公開しました',
    description: 'Roomly.の公式サービスサイトを公開しました。',
    body: ['Roomly.の公式サービスサイトを公開しました。'],
  },
  {
    slug: 'roomly-multilingual-2026-03-20',
    date: '2026.03.20',
    category: 'サービス',
    title: 'Roomly. 多言語対応機能を実装しました',
    description: '訪日外国人向けの多言語チャット機能を実装しました。',
    body: ['訪日外国人向けの多言語チャット機能を実装しました。'],
  },
  {
    slug: 'roomly-service-page-2026-02-25',
    date: '2026.02.25',
    category: 'サービス',
    title: 'Roomly. サービス紹介ページを公開しました',
    description: 'Roomly.の概要をご確認いただけるページを公開しました。',
    body: ['Roomly.の概要をご確認いただけるページを公開しました。'],
  },
  {
    slug: 'roomly-prototype-2026-02-15',
    date: '2026.02.15',
    category: 'サービス',
    title: 'Roomly. プロトタイプ版が完成しました',
    description: '初期バージョンの開発が完了しました。',
    body: ['初期バージョンの開発が完了しました。'],
  },
  {
    slug: 'roomly-logo-2026-02-10',
    date: '2026.02.10',
    category: 'お知らせ',
    title: 'Roomly. ブランドロゴを公開しました',
    description: 'Roomly.のサービスロゴを公開しました。',
    body: ['Roomly.のサービスロゴを公開しました。'],
  },
  {
    slug: 'roomly-development-start-2026-01-29',
    date: '2026.01.29',
    category: 'サービス',
    title: 'Roomly.の開発を開始しました',
    description: 'ホテル向けAIチャットサービスの開発を開始しました。',
    body: ['ホテル向けAIチャットサービスの開発を開始しました。'],
  },
  {
    slug: 'partner-program-start-2026-01-25',
    date: '2026.01.25',
    category: 'プレスリリース',
    title: 'パートナー制度を開始しました',
    description: '企業や個人事業主向けのパートナー制度を開始しました。',
    body: ['企業や個人事業主向けのパートナー制度を開始しました。'],
  },
  {
    slug: 'partner-program-preparation-2026-01-10',
    date: '2026.01.10',
    category: 'お知らせ',
    title: 'MOGCIAパートナー制度の準備を開始しました',
    description: '販売パートナー・紹介パートナー制度の整備を開始しました。',
    body: ['販売パートナー・紹介パートナー制度の整備を開始しました。'],
  },
  {
    slug: 'upmo-site-2025-12-15',
    date: '2025.12.15',
    category: 'プレスリリース',
    title: 'upmo サービスサイトを公開しました',
    description: 'upmoの公式サービスサイトを公開しました。',
    body: ['upmoの公式サービスサイトを公開しました。'],
  },
  {
    slug: 'upmo-permission-2025-12-01',
    date: '2025.12.01',
    category: 'サービス',
    title: 'upmo 権限管理機能を追加しました',
    description: '閲覧権限を柔軟に管理できる機能を追加しました。',
    body: ['閲覧権限を柔軟に管理できる機能を追加しました。'],
  },
  {
    slug: 'upmo-ui-renewal-2025-11-15',
    date: '2025.11.15',
    category: 'サービス',
    title: 'upmo UIリニューアルを実施しました',
    description: '検索体験向上のため画面デザインを改善しました。',
    body: ['検索体験向上のため画面デザインを改善しました。'],
  },
  {
    slug: 'upmo-test-introduction-2025-11-01',
    date: '2025.11.01',
    category: 'サービス',
    title: 'upmo テスト導入を開始しました',
    description: '一部企業様を対象に試験運用を開始しました。',
    body: ['一部企業様を対象に試験運用を開始しました。'],
  },
  {
    slug: 'upmo-prototype-2025-10-15',
    date: '2025.10.15',
    category: 'サービス',
    title: 'upmo プロトタイプ版が完成しました',
    description: '主要機能の初期開発が完了しました。',
    body: ['主要機能の初期開発が完了しました。'],
  },
  {
    slug: 'upmo-knowledge-search-2025-10-01',
    date: '2025.10.01',
    category: 'サービス',
    title: 'upmo ナレッジ検索機能の開発を開始しました',
    description: '社内資料や議事録を横断検索できる機能の開発を開始しました。',
    body: ['社内資料や議事録を横断検索できる機能の開発を開始しました。'],
  },
  {
    slug: 'upmo-concept-page-2025-09-25',
    date: '2025.09.25',
    category: 'サービス',
    title: 'upmo サービス構想ページを公開しました',
    description: '開発背景やサービスコンセプトを公開しました。',
    body: ['開発背景やサービスコンセプトを公開しました。'],
  },
  {
    slug: 'upmo-logo-2025-09-15',
    date: '2025.09.15',
    category: 'お知らせ',
    title: 'upmo ブランドロゴを公開しました',
    description: 'upmoのブランドロゴを公開しました。',
    body: ['upmoのブランドロゴを公開しました。'],
  },
  {
    slug: 'upmo-development-start-2025-09-01',
    date: '2025.09.01',
    category: 'サービス',
    title: '社内AI検索システム「upmo」の開発を開始しました',
    description: '社内ナレッジをAIで検索できるサービスとして開発を開始しました。',
    body: ['社内ナレッジをAIで検索できるサービスとして開発を開始しました。'],
  },
  {
    slug: 'signal-ui-renewal-2025-08-15',
    date: '2025.08.15',
    category: 'サービス',
    title: 'Signal. UIをリニューアルしました',
    description: 'より直感的に利用できるデザインへ改善しました。',
    body: ['より直感的に利用できるデザインへ改善しました。'],
  },
  {
    slug: 'signal-beta-2025-08-01',
    date: '2025.08.01',
    category: 'サービス',
    title: 'Signal. β版の提供を開始しました',
    description: '正式リリースに向けたβ版の提供を開始しました。',
    body: ['正式リリースに向けたβ版の提供を開始しました。'],
  },
  {
    slug: 'signal-pricing-2025-07-20',
    date: '2025.07.20',
    category: 'サービス',
    title: 'Signal. 料金プランを公開しました',
    description: 'サービス導入をご検討中のお客様向けに料金プランを公開しました。',
    body: ['サービス導入をご検討中のお客様向けに料金プランを公開しました。'],
  },
  {
    slug: 'signal-site-2025-07-10',
    date: '2025.07.10',
    category: 'プレスリリース',
    title: 'Signal. サービスサイトを公開しました',
    description: 'サービス概要や料金プランをご確認いただける公式サイトを公開しました。',
    body: ['サービス概要や料金プランをご確認いただける公式サイトを公開しました。'],
  },
  {
    slug: 'signal-report-2025-06-25',
    date: '2025.06.25',
    category: 'サービス',
    title: 'Signal. レポート機能を追加しました',
    description: '運用結果を分かりやすく確認できるレポート機能を追加しました。',
    body: ['運用結果を分かりやすく確認できるレポート機能を追加しました。'],
  },
  {
    slug: 'signal-analysis-update-2025-06-15',
    date: '2025.06.15',
    category: 'サービス',
    title: 'Signal. 分析機能をアップデートしました',
    description: 'アカウント分析の精度向上とレポート内容の改善を実施しました。',
    body: ['アカウント分析の精度向上とレポート内容の改善を実施しました。'],
  },
  {
    slug: 'signal-test-introduction-2025-06-01',
    date: '2025.06.01',
    category: 'サービス',
    title: 'Signal. テスト導入を開始しました',
    description: '一部企業様を対象とした試験導入を開始しました。',
    body: ['一部企業様を対象とした試験導入を開始しました。'],
  },
  {
    slug: 'signal-admin-development-2025-05-15',
    date: '2025.05.15',
    category: 'サービス',
    title: 'Signal. 管理画面の開発を開始しました',
    description: '分析結果を分かりやすく可視化するダッシュボードの開発を開始しました。',
    body: ['分析結果を分かりやすく可視化するダッシュボードの開発を開始しました。'],
  },
  {
    slug: 'signal-prototype-2025-05-01',
    date: '2025.05.01',
    category: 'サービス',
    title: 'Signal. プロトタイプ版が完成しました',
    description: '主要機能の実装が完了し、初期検証を開始しました。',
    body: ['主要機能の実装が完了し、初期検証を開始しました。'],
  },
  {
    slug: 'signal-concept-page-2025-04-20',
    date: '2025.04.20',
    category: 'サービス',
    title: 'Signal. サービス構想ページを公開しました',
    description: 'Signal.の開発背景や提供価値を紹介するページを公開しました。',
    body: ['Signal.の開発背景や提供価値を紹介するページを公開しました。'],
  },
  {
    slug: 'signal-logo-2025-04-10',
    date: '2025.04.10',
    category: 'お知らせ',
    title: 'Signal. ブランドロゴを公開しました',
    description: 'Signal.のサービスブランドを象徴するロゴデザインを公開しました。',
    body: ['Signal.のサービスブランドを象徴するロゴデザインを公開しました。'],
  },
  {
    slug: 'signal-development-start-2025-04-01',
    date: '2025.04.01',
    category: 'サービス',
    title: 'Instagram運用AI「Signal.」の開発を開始しました',
    description: '企業のSNS運用を効率化するAIサービスとして開発を開始しました。',
    body: ['企業のSNS運用を効率化するAIサービスとして開発を開始しました。'],
  },
  {
    slug: 'sns-service-system-2025-03-10',
    date: '2025.03.10',
    category: 'サービス',
    title: 'SNS運用サービスの提供体制を強化しました',
    description: '企画・制作・分析までを一貫して支援できる体制を整備しました。',
    body: ['企画・制作・分析までを一貫して支援できる体制を整備しました。'],
  },
  {
    slug: 'sns-management-service-2025-03-01',
    date: '2025.03.01',
    category: 'サービス',
    title: 'SNS運用代行サービスの提供を開始しました',
    description: 'Instagramを中心としたSNS運用代行サービスの提供を開始しました。',
    body: ['Instagramを中心としたSNS運用代行サービスの提供を開始しました。'],
  },
  {
    slug: 'lp-production-service-2025-02-15',
    date: '2025.02.15',
    category: 'サービス',
    title: 'LP制作サービスの提供を開始しました',
    description: '集客や採用、問い合わせ獲得を目的としたランディングページ制作サービスを開始しました。',
    body: ['集客や採用、問い合わせ獲得を目的としたランディングページ制作サービスを開始しました。'],
  },
  {
    slug: 'web-production-service-2025-02-01',
    date: '2025.02.01',
    category: 'サービス',
    title: 'Web制作サービスの提供を開始しました',
    description: '企業の目的や課題に合わせたコーポレートサイト・サービスサイトの制作支援を開始しました。',
    body: ['企業の目的や課題に合わせたコーポレートサイト・サービスサイトの制作支援を開始しました。'],
  },
  {
    slug: 'coffee-christmas-set-2024-12-24',
    date: '2024.12.24',
    category: 'お知らせ',
    title: 'MOGCIA Coffee クリスマス限定セットの販売を開始しました',
    description: '数量限定のクリスマスセットを販売開始しました。',
    body: ['数量限定のクリスマスセットを販売開始しました。'],
  },
  {
    slug: 'coffee-year-end-campaign-2024-12-10',
    date: '2024.12.10',
    category: 'お知らせ',
    title: 'MOGCIA Coffee 年末キャンペーンを開始しました',
    description: '期間限定のキャンペーンを実施しました。',
    body: ['期間限定のキャンペーンを実施しました。'],
  },
  {
    slug: 'coffee-popup-choosebase-2024-12-01',
    date: '2024.12.01',
    category: 'お知らせ',
    title: 'Choosebase SHIBUYA にてPOPUP販売を実施しました',
    description: '期間限定でPOPUP販売を実施しました。',
    body: ['期間限定でPOPUP販売を実施しました。'],
  },
  {
    slug: 'coffee-oem-service-2024-11-20',
    date: '2024.11.20',
    category: 'サービス',
    title: '企業向けOEMコーヒーサービスの提供を開始しました',
    description: '企業オリジナルコーヒーのOEM提供を開始しました。',
    body: ['企業オリジナルコーヒーのOEM提供を開始しました。'],
  },
  {
    slug: 'coffee-gift-measures-2024-11-15',
    date: '2024.11.15',
    category: 'お知らせ',
    title: 'MOGCIA Coffee ギフト需要向け施策を開始しました',
    description: '年末シーズンに向けたギフト展開を開始しました。',
    body: ['年末シーズンに向けたギフト展開を開始しました。'],
  },
  {
    slug: 'coffee-package-renewal-2024-11-11',
    date: '2024.11.11',
    category: 'お知らせ',
    title: 'MOGCIA Coffee パッケージをリニューアルしました',
    description: 'ブランドイメージの向上を目的にパッケージデザインを刷新しました。',
    body: ['ブランドイメージの向上を目的にパッケージデザインを刷新しました。'],
  },
  {
    slug: 'coffee-winter-package-2024-11-01',
    date: '2024.11.01',
    category: 'お知らせ',
    title: 'MOGCIA Coffee 冬季限定パッケージを公開しました',
    description: '冬シーズン向けのデザインを公開しました。',
    body: ['冬シーズン向けのデザインを公開しました。'],
  },
  {
    slug: 'coffee-product-page-renewal-2024-10-20',
    date: '2024.10.20',
    category: 'お知らせ',
    title: 'MOGCIA Coffee 商品ページをリニューアルしました',
    description: '商品の魅力が伝わりやすいページへ改善しました。',
    body: ['商品の魅力が伝わりやすいページへ改善しました。'],
  },
  {
    slug: 'coffee-sales-channel-2024-10-10',
    date: '2024.10.10',
    category: 'お知らせ',
    title: 'MOGCIA Coffee 販売チャネルを拡大しました',
    description: 'より多くのお客様へお届けできるよう販売経路を拡大しました。',
    body: ['より多くのお客様へお届けできるよう販売経路を拡大しました。'],
  },
  {
    slug: 'yamada-mall-2024-10-01',
    date: '2024.10.01',
    category: 'お知らせ',
    title: 'ヤマダモールに出店しました',
    description: 'ヤマダ電機のオンラインショップにて販売を開始しました。',
    body: ['ヤマダ電機のオンラインショップにて販売を開始しました。'],
  },
  {
    slug: 'coffee-gift-2024-09-15',
    date: '2024.09.15',
    category: 'お知らせ',
    title: 'MOGCIA Coffee ギフト対応を開始しました',
    description: 'ギフト用途でご利用いただけるラッピング対応を開始しました。',
    body: ['ギフト用途でご利用いただけるラッピング対応を開始しました。'],
  },
  {
    slug: 'coffee-first-shipment-2024-09-05',
    date: '2024.09.05',
    category: 'お知らせ',
    title: 'MOGCIA Coffee 初回出荷を開始しました',
    description: 'ご注文いただいた商品の発送を開始しました。',
    body: ['ご注文いただいた商品の発送を開始しました。'],
  },
  {
    slug: 'coffee-online-store-2024-09-01',
    date: '2024.09.01',
    category: 'お知らせ',
    title: 'MOGCIA Coffee オンライン販売を開始しました',
    description: '公式オンラインストアにて販売を開始しました。',
    body: ['公式オンラインストアにて販売を開始しました。'],
  },
  {
    slug: 'coffee-teaser-2024-08-20',
    date: '2024.08.20',
    category: 'お知らせ',
    title: 'MOGCIA Coffee ティザー情報を公開しました',
    description: '販売開始に先駆けてブランド情報を公開しました。',
    body: ['販売開始に先駆けてブランド情報を公開しました。'],
  },
  {
    slug: 'coffee-package-design-2024-08-10',
    date: '2024.08.10',
    category: 'お知らせ',
    title: 'MOGCIA Coffee パッケージデザイン制作を開始しました',
    description: '商品の世界観を表現するパッケージ制作に着手しました。',
    body: ['商品の世界観を表現するパッケージ制作に着手しました。'],
  },
  {
    slug: 'coffee-product-development-2024-04-01',
    date: '2024.04.01',
    category: 'お知らせ',
    title: 'MOGCIA Coffee 商品開発を開始しました',
    description: 'オリジナルブレンドコーヒーの開発を開始しました。',
    body: ['オリジナルブレンドコーヒーの開発を開始しました。'],
  },
  {
    slug: 'coffee-logo-2024-03-15',
    date: '2024.03.15',
    category: 'お知らせ',
    title: 'MOGCIA Coffee ブランドロゴを公開しました',
    description: 'MOGCIA Coffeeのブランドロゴを公開しました。',
    body: ['MOGCIA Coffeeのブランドロゴを公開しました。'],
  },
  {
    slug: 'coffee-project-start-2024-03-01',
    date: '2024.03.01',
    category: 'お知らせ',
    title: 'MOGCIA Coffeeプロジェクトを開始しました',
    description: 'MOGCIA初のオリジナルブランドとして、MOGCIA Coffeeプロジェクトを開始しました。',
    body: ['MOGCIA初のオリジナルブランドとして、MOGCIA Coffeeプロジェクトを開始しました。'],
  },
]
